// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using ServiceDashBoard1.Data;

#nullable disable

namespace ServiceDashBoard1.Migrations
{
    [DbContext(typeof(ServiceDashBoard1Context))]
    [Migration("20250718050456_OptionImagebase64")]
    partial class OptionImagebase64
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            modelBuilder.Entity("ServiceDashBoard1.Models.ComplaintRegistration", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<string>("Address")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("CheckedBy")
                        .HasColumnType("TEXT");

                    b.Property<string>("CompanyName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("ComplaintDescription")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("ContactPerson")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("datetime");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("EmployeeId1")
                        .HasColumnType("TEXT");

                    b.Property<string>("EmployeeName1")
                        .HasColumnType("TEXT");

                    b.Property<string>("ImageBase64")
                        .HasColumnType("TEXT");

                    b.Property<string>("MachineSerialNo")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("ModifiedDate")
                        .HasColumnType("datetime");

                    b.Property<string>("PhoneNo")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Role")
                        .HasColumnType("TEXT");

                    b.Property<string>("SelectedMainProblems")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("SelectedSubProblems")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("TokenId")
                        .HasColumnType("int");

                    b.Property<string>("TokenNumber")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("TokenId");

                    b.ToTable("ComplaintRegistration");
                });

            modelBuilder.Entity("ServiceDashBoard1.Models.CustomerRegistration", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<string>("CompanyAddress")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("CompanyName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("ContactPersonName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("CreatedDate")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("MachineSerialNo")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("MachineType")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("ModifiedDate")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("PhoneNo")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Role")
                        .HasColumnType("TEXT");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("isActive")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("EmployeeRegistration");
                });

            modelBuilder.Entity("ServiceDashBoard1.Models.EmployeeAssignComplaint", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<int>("ComplaintRegistrationId")
                        .HasColumnType("int");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("EmployeeIdNo")
                        .HasColumnType("TEXT");

                    b.Property<string>("EmployeeNames")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("ComplaintRegistrationId");

                    b.ToTable("EmployeeAssignComplaints");
                });

            modelBuilder.Entity("ServiceDashBoard1.Models.MachineDetails", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("SR NO");

                    b.Property<string>("CompanyAddress")
                        .IsRequired()
                        .HasColumnType("Text")
                        .HasColumnName("CUSTOMER_ADDRESS");

                    b.Property<string>("CompanyName")
                        .IsRequired()
                        .HasColumnType("Text")
                        .HasColumnName("CUSTOMER NAME");

                    b.Property<string>("ContactPerson")
                        .IsRequired()
                        .HasColumnType("Text")
                        .HasColumnName("INSTALLATION  DONE BY");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("Text")
                        .HasColumnName("EMAIL ID");

                    b.Property<string>("MachineSerialNumber")
                        .IsRequired()
                        .HasColumnType("Text")
                        .HasColumnName("M_C NO");

                    b.Property<string>("PhoneNo")
                        .IsRequired()
                        .HasColumnType("Text")
                        .HasColumnName("CONTACT NO");

                    b.HasKey("Id");

                    b.ToTable("MasterData");
                });

            modelBuilder.Entity("ServiceDashBoard1.Models.RemarkHistory", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<int>("ComplaintId")
                        .HasColumnType("int");

                    b.Property<string>("RemarkBy")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("RemarkDate")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("RemarkText")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("RemarkHistories");
                });

            modelBuilder.Entity("ServiceDashBoard1.Models.ServiceModel", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<int>("ComplaintId")
                        .HasColumnType("int");

                    b.Property<string>("FinalRemark")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("FinalRemarkBy")
                        .HasColumnType("TEXT");

                    b.Property<string>("Remark")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("RemarkBy")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("ServiceModels");
                });

            modelBuilder.Entity("ServiceDashBoard1.Models.TokenSequence", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<int>("NextEmployeeId")
                        .HasColumnType("int");

                    b.Property<int>("NextTokenNumber")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("TokenSequences");
                });

            modelBuilder.Entity("ServiceDashBoard1.Models.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<string>("Address")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("CreatedDate")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("EmailId")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("EmployeeId")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsFirstLogin")
                        .HasColumnType("tinyint(1)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<long>("PhoneNo")
                        .HasColumnType("bigint");

                    b.Property<string>("Role")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<bool>("ShowPasswordChangePopup")
                        .HasColumnType("tinyint(1)");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("isActive")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("User");
                });

            modelBuilder.Entity("ServiceDashBoard1.Models.ComplaintRegistration", b =>
                {
                    b.HasOne("ServiceDashBoard1.Models.TokenSequence", "TokenSequence")
                        .WithMany()
                        .HasForeignKey("TokenId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("TokenSequence");
                });

            modelBuilder.Entity("ServiceDashBoard1.Models.EmployeeAssignComplaint", b =>
                {
                    b.HasOne("ServiceDashBoard1.Models.ComplaintRegistration", "Complaint")
                        .WithMany("EmployeeAssignments")
                        .HasForeignKey("ComplaintRegistrationId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Complaint");
                });

            modelBuilder.Entity("ServiceDashBoard1.Models.ComplaintRegistration", b =>
                {
                    b.Navigation("EmployeeAssignments");
                });
#pragma warning restore 612, 618
        }
    }
}
